site_name: 'backstagetest-python-app-12'
site_description: 'Main documentation for the backstagetest-python-app-12'
repo_url: https://github.com/CodeArchipelago/backstagetest-python-app-12
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'